import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { basename, dirname, join, extname } from 'node:path';
import { runShellCommand } from '../utils/shell.js';
import type { Task, PRDMeta } from '../prd/schemas.js';
import type { LLMClient } from '../llm/client.js';
import type { ToolRegistry } from '../tools/types.js';
import { buildScaffoldPrompt } from './prompts.js';

export interface ScaffoldOptions {
  /** Tasks to scaffold files/tests for. */
  tasks: Task[];
  /** Included for future LLM-driven scaffolding. */
  llmClient?: LLMClient | undefined;
  /** Included for future LLM-driven scaffolding. */
  tools?: ToolRegistry | undefined;
  projectRoot: string;
  meta: PRDMeta;
}

export interface ScaffoldResult {
  filesCreated: string[];
  testsCreated: string[];
  success: boolean;
  errors: string[];
}

/**
 * Create minimal compilable stubs for planned files and test shells.
 */
export async function runScaffold(
  options: ScaffoldOptions,
): Promise<ScaffoldResult> {
  const { tasks, projectRoot, meta } = options;
  const scaffoldPrompt = buildScaffoldPrompt(tasks, {
    projectRoot,
    maxTokens: 4096,
    projectContext: `Tech stack: ${meta.techStack}`,
  });
  void scaffoldPrompt;

  const filesCreated: string[] = [];
  const testsCreated: string[] = [];
  const errors: string[] = [];

  const testTodos = collectTestTodos(tasks);
  const testPaths = new Set(Array.from(testTodos.keys()));
  const filePaths = new Set(
    tasks.flatMap((task) => task.files).filter((p) => p.trim().length > 0),
  );

  for (const filePath of filePaths) {
    if (testPaths.has(filePath)) continue;
    const absPath = join(projectRoot, filePath);
    if (existsSync(absPath)) continue;

    mkdirSync(dirname(absPath), { recursive: true });
    writeFileSync(absPath, buildSourceStub(filePath), 'utf-8');
    filesCreated.push(filePath);
  }

  for (const [testPath, todos] of testTodos.entries()) {
    const absPath = join(projectRoot, testPath);
    if (existsSync(absPath)) continue;

    mkdirSync(dirname(absPath), { recursive: true });
    writeFileSync(absPath, buildTestStub(testPath, todos), 'utf-8');
    testsCreated.push(testPath);
  }

  const typecheck = await runShellCommand(meta.typecheckCommand, {
    cwd: projectRoot,
    timeoutMs: 120000,
  });
  if (typecheck.exitCode !== 0 || typecheck.timedOut) {
    errors.push(
      `Typecheck failed after scaffold:\n${[typecheck.stdout, typecheck.stderr].filter(Boolean).join('\n')}`,
    );
  }

  if (testsCreated.length > 0) {
    const testCommand = buildTestDiscoveryCommand(meta.testFramework);
    if (testCommand) {
      const testRun = await runShellCommand(testCommand, {
        cwd: projectRoot,
        timeoutMs: 120000,
      });
      if (testRun.exitCode !== 0 || testRun.timedOut) {
        errors.push(
          `Test discovery failed after scaffold:\n${[testRun.stdout, testRun.stderr].filter(Boolean).join('\n')}`,
        );
      }
    }
  }

  return {
    filesCreated,
    testsCreated,
    success: errors.length === 0,
    errors,
  };
}

function collectTestTodos(tasks: Task[]): Map<string, string[]> {
  const map = new Map<string, string[]>();

  for (const task of tasks) {
    for (const testPath of task.tests) {
      const entries = map.get(testPath) ?? [];
      const todo = `${task.id}: ${task.title}`;
      if (!entries.includes(todo)) {
        entries.push(todo);
      }
      map.set(testPath, entries);
    }
  }

  return map;
}

function buildSourceStub(filePath: string): string {
  const ext = extname(filePath).toLowerCase();

  if (ext === '.json') {
    return '{}\n';
  }

  if (['.md', '.txt', '.yml', '.yaml'].includes(ext)) {
    return '';
  }

  return [
    '// Scaffold stub generated by AgentLoop Phase 1.',
    'export {};',
    '',
  ].join('\n');
}

function buildTestStub(testPath: string, todos: string[]): string {
  const suiteName = basename(testPath).replace(/\.[^.]+$/, '');
  const lines: string[] = [
    "import { describe, it } from 'vitest';",
    '',
    `describe('${escapeForSingleQuote(suiteName)}', () => {`,
  ];

  for (const todo of todos) {
    lines.push(`  it.todo('${escapeForSingleQuote(todo)}');`);
  }

  lines.push('});', '');
  return lines.join('\n');
}

function buildTestDiscoveryCommand(testFramework: string): string | null {
  const trimmed = testFramework.trim();
  if (!trimmed) return null;

  if (/\s/.test(trimmed)) {
    return trimmed;
  }

  if (trimmed === 'node:test') {
    return 'node --test';
  }

  if (trimmed.includes('vitest') || trimmed.includes('jest')) {
    return `${trimmed} run`;
  }

  return trimmed;
}

function escapeForSingleQuote(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}
