import fs from 'node:fs';
import path from 'node:path';

export async function execute({ workingDirectory, instructions, branchName }) {
  // Create a stub implementation file based on the branch name
  const fileName = `${branchName}.md`;
  const filePath = path.join(workingDirectory, fileName);
  const content = [
    `# Implementation: ${branchName}`,
    '',
    '> Auto-generated by Scarlet mock agent',
    '',
    '## Instructions received',
    '',
    instructions,
  ].join('\n');

  fs.writeFileSync(filePath, content + '\n');

  return {
    success: true,
    filesChanged: [fileName],
    logs: `Mock agent created ${fileName}`,
  };
}
